language: node_js
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "ciroreed@gmail.com"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8
  - 10
before_script:
  - npm install
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
